### ISSUE TITLE
2FA support?

### ISSUE THREAD

**Issue by l8nite** [trevorwelch/rh-profit-and-loss#5]
```Working...
Traceback (most recent call last):
  File "get_profit_and_loss.py", line 324, in <module>
    pickle=pickle)
  File "get_profit_and_loss.py", line 90, in rh_profit_and_loss
    logged_in = my_trader.login(username=username, password=password)
  File "rh-profit-and-loss/Robinhood.py", line 117, in login
    raise RH_exception.TwoFactorRequired()  # requires a second call to enable 2FA
exceptions.TwoFactorRequired
```

**Comment by hududed** [comment]
I am facing the same issue. Any plans to make two-factor authentication work?

**Comment by trevorwelch** [comment]
Thanks for your interest in this project @l8nite @hududed  ... Unfortunately I haven't had time to maintain this since jumping into an engineering role at a startup. I would totally welcome a PR though. I'm not sure if the Jamonek framework has a good flow for 2FA or not, but feel free to fork my code and make a PR!

**Comment by imatech** [comment]
What's a PR?
I was hoping to find a python script to analyze spreadsheets of transactions...any suggestions on that?
